# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'ARM-PipelineConnection'
    subscriptionId: 'cd368f2a-97b1-4038-8a31-494775e64b98'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'BAT-GLOBAL-BR-DEV'
    location: 'Brazil South'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://raw.githubusercontent.com/estevesm/arm-bat-global/main/azuredeploy.json?token=GHSAT0AAAAAACQ3UWPG3HGIWQSCMH6J4ARKZQZDWQA'
    deploymentMode: 'Incremental'
    deploymentName: 'ARMDeploy'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
